
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 29;
  public static final int C_PAREN = 32;
  public static final int O_PAREN = 31;
  public static final int INT = 12;
  public static final int PRINTLN = 18;
  public static final int O_CBRACKET = 35;
  public static final int OUT = 4;
  public static final int MINUS = 27;
  public static final int STATIC = 7;
  public static final int SEMICOLON = 37;
  public static final int AND = 30;
  public static final int CLASS = 11;
  public static final int PLUS = 24;
  public static final int MAIN = 9;
  public static final int IF = 15;
  public static final int THIS = 20;
  public static final int O_SBRACKET = 33;
  public static final int EOF = 0;
  public static final int BOOLEAN = 13;
  public static final int SYSTEM = 3;
  public static final int RETURN = 10;
  public static final int TRUE = 23;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int COMA = 38;
  public static final int NEGATION = 26;
  public static final int VOID = 8;
  public static final int EQ = 25;
  public static final int ELSE = 17;
  public static final int C_CBRACKET = 36;
  public static final int POINT = 39;
  public static final int WHILE = 16;
  public static final int PUBLIC = 6;
  public static final int EXTENDS = 5;
  public static final int STRING = 14;
  public static final int FALSE = 22;
  public static final int SUB = 28;
  public static final int PRINT = 2;
  public static final int LENGTH = 19;
  public static final int C_SBRACKET = 34;
  public static final int INTEGER_LITERAL = 41;
  public static final int IDENTIFIER = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "SYSTEM",
  "OUT",
  "EXTENDS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "RETURN",
  "CLASS",
  "INT",
  "BOOLEAN",
  "STRING",
  "IF",
  "WHILE",
  "ELSE",
  "PRINTLN",
  "LENGTH",
  "THIS",
  "NEW",
  "FALSE",
  "TRUE",
  "PLUS",
  "EQ",
  "NEGATION",
  "MINUS",
  "SUB",
  "MULT",
  "AND",
  "O_PAREN",
  "C_PAREN",
  "O_SBRACKET",
  "C_SBRACKET",
  "O_CBRACKET",
  "C_CBRACKET",
  "SEMICOLON",
  "COMA",
  "POINT",
  "IDENTIFIER",
  "INTEGER_LITERAL"
  };
}

